# x=input()
# c=0
# for i in x:
#     c+=int(i)
# print(c)

# x=input()

# for i in x:
#     if int(i)%2!=0:
#         print(i,end="")

# x=input()

# for i in x:
#     if int(i)%2==0:
#         print(i,end="")

# l=["a","e","i","o,","u"]
# s=input().lower()
# vv=""
# co=""
# cc=0
# v=0
# for i in s:
#     if i in l:
#         vv+=i
#         v+=1
#     elif i not in l:
#         co+=i
#         cc+=1
# print(f"vowels={vv} count={v} & constants={co} count={cc}")

# n=input()
# o=""
# for i in range(len(n)-1,-1,-1):
#     o+= n[i]
# print(o)
